### ISSUE TITLE
BUG -   Does not work with ts file

### ISSUE THREAD

**Issue by Eskiell** [huzaifahj/slot-calculator#1]
simulate :

Create a project with npx tsc --init
npm install slot-calculator

create a file  temp.ts  and put the code exemple from doc
import { getSlots } from "slot-calculator"
const { allSlots } = getSlots({
  from: "2022-01-01",
  to: "2022-01-02",
  duration: 60,
})

run : ts-node temp.ts

Error [ERR_REQUIRE_ESM]: require() of ES Module \node_modules\slot-calculator\dist\index.js from  \Documents\Dates\temp.ts not supported.
Instead change the require of index.js in Documents\Dates\temp.ts to a dynamic import() which is available in all CommonJS modules

**Comment by huzaifahj** [comment]
Thanks for submitting an issue @Eskiell , I will look into this

**Comment by ckasthuriarachchi** [comment]
@huzaifahj Im getting the same error . Please help!

![image](https://user-images.githubusercontent.com/15852872/178586541-adfe3765-f94a-4396-afa1-d685ccd54bec.png)

**Comment by huzaifahj** [comment]
@Eskiell @ckasthuriarachchi This should be fixed now in the latest release. Thanks to @farazahmadkhan15

**Comment by Eskiell** [comment]
thanks
