### ISSUE TITLE
slots are shifted

### ISSUE THREAD

**Issue by Kepro** [huzaifahj/slot-calculator#6]
Hello, I'm working on my side project for booking, and there is one issue, 
the configuration you have business hours 9-5, event duration is 60 minutes, but for some reason, you need to move one person by 15 minutes, but that will affect all future slots... 
![image](https://user-images.githubusercontent.com/1714370/218281807-6c096f7e-1c8a-45c1-83ce-ba45af4a7bac.png)

is it possible to provide an option if "slots" should remain respected?

**Comment by Kepro** [comment]
nevermind I solved it with :-) 
```typescript
function roundToHour(date: string | Date) {
  const d = date instanceof Date ? date : new Date(date);
  const p = 60 * 60 * 1000; // milliseconds in an hour
  return new Date(Math.ceil(d.getTime() / p ) * p);
}
```

**Comment by huzaifahj** [comment]
Thanks for creating this issue @Kepro 

Glad you sorted it out but is there a way the library could better support this use case?

**Comment by Kepro** [comment]
I don't want to overengineer the library, but if there is a simple way hot to respect `duration` between slots, (as example above)
