### ISSUE TITLE
Daylight Savings Time Bug

### ISSUE THREAD

**Issue by iamnafets** [huzaifahj/slot-calculator#9]
These lines fail on daylight savings time.

https://github.com/huzaifahj/slot-calculator/blob/7d0b064ed0d266315318ea1fd367abd05f3269db/index.ts#L215-L237

The DST shift (e.g. on May 10th) moves forward at 2am, pushing slots +- 1 hour.

**Comment by huzaifahj** [comment]
Thank you! Closed in latest version
